% Creates GUI for pressure control
% boxes for time delay and set point
% buttons to start and stop
% callbacks created by main function.
% Maya Dunn

% Last Updated - 3/16/15

function fig = pressureControlGUI(varargin)
    x = 500;
    y = 150;
    
        %fig.GUI.Units = 'normalized';
        
    % Close old, create, hide
    fig.guiName = 'pressureControl';
    
    oldFigs = findobj('tag',fig.guiName);
    delete(oldFigs)
    
    fig.GUI = figure('Visible','off',...
            'Position',[200 400 x y],...
            'tag',fig.guiName);
        
    set(fig.GUI,'MenuBar','none');
    set(fig.GUI, 'units','normalized');
    
    dx = (1-2*.02)/2/2
    dy = (1-2*.02)/9

    xg = .02:dx:1-.02
    yg = 1-dy-.02:-(dy):.02
    buttonSize = [dx, .85*dy]
    labelSize = [dx*2, .75*dy]
    
    fig.runningLabel = uicontrol('Style','text',...
            'Position',[xg(1) yg(1) labelSize],...
            'String','Not Running');
    fig.readout = uicontrol('Style','text',...
            'Position',[xg(1) yg(2) labelSize],...
            'String','', 'tooltip','[heating, pressure]');
    fig.steadyStateLabel = uicontrol('Style','text',...
            'Position',[xg(3) yg(3) buttonSize],...
            'String','Steady State Heating (0.00)', 'tooltip','A heating percent close to the equillibrium state');
    fig.kPLabel = uicontrol('Style','text',...
            'Position',[xg(1) yg(4) buttonSize],...
            'String','KP', 'tooltip','Proportional Response Constant');
    fig.kP = uicontrol('Style','edit',...
            'Position',[xg(2) yg(4) buttonSize],...
            'String','.3', 'tooltip','Proportional Response Constant');
        
    fig.kILabel = uicontrol('Style','text',...
            'Position',[xg(1) yg(5) buttonSize],...
            'String','KI', 'tooltip','Integrated Response Constant');
    fig.kI = uicontrol('Style','edit',...
            'Position',[xg(2) yg(5) buttonSize],...
            'String','.05', 'tooltip','Integrated Response Constant');
    fig.setPointLabel = uicontrol('Style','text',...
            'Position',[xg(1) yg(6) buttonSize],...
            'String','Pressure Set Point', 'tooltip','Desired Pressure');
    fig.setPoint = uicontrol('Style','edit',...
            'Position',[xg(2) yg(6) buttonSize],...
              'tooltip','Desired Pressure');
    fig.timeDelayLabel = uicontrol('Style','text',...
            'Position',[xg(1) yg(7) buttonSize],...
            'String','time delay (seconds)', 'tooltip','Cycle Period');
    fig.delay = uicontrol('Style','edit',...
            'Position',[xg(2) yg(7) buttonSize],...
            'String','5', 'tooltip','Cycle Period');
    fig.changeSettings = uicontrol('Style','pushButton',...
            'Position',[xg(1) yg(8) labelSize],...
            'String','Change Settings');
    fig.stop = uicontrol('Style','pushButton',...
            'Position',[xg(1) yg(9) buttonSize],...
            'String','Stop',...
            'tooltip','Stop Doing Pressure Control');
    fig.start = uicontrol('Style','pushButton',...
            'Position',[xg(2) yg(9) buttonSize],...
            'String','Start',...
            'tooltip','Start Doing Pressure Control');
        
    fig.runningLabel2 = uicontrol('Style','text',...
            'Position',[xg(3) yg(1) labelSize],...
            'String','Not Running');
    fig.readout2 = uicontrol('Style','text',...
            'Position',[xg(3) yg(2) labelSize],...
            'String','', 'tooltip','[heating, pressure]');
    fig.steadyState2 = uicontrol('Style','edit',...
            'Position',[xg(3) yg(3) buttonSize],...
            'String','.3', 'tooltip','A heating percent close to the equillibrium state');
    fig.kP2 = uicontrol('Style','edit',...
            'Position',[xg(3) yg(4) buttonSize],...
            'String','.3', 'tooltip','Proportional Response Constant');
    fig.kI2 = uicontrol('Style','edit',...
            'Position',[xg(3) yg(5) buttonSize],...
            'String','.05', 'tooltip','Integrated Response Constant');
    fig.setPoint2 = uicontrol('Style','edit',...
            'Position',[xg(3) yg(6) buttonSize],...
              'tooltip','Desired Pressure');
    fig.delay2 = uicontrol('Style','edit',...
            'Position',[xg(3) yg(7) buttonSize],...
            'String','5', 'tooltip','Cycle Period');
    fig.changeSettings2 = uicontrol('Style','pushButton',...
            'Position',[xg(3) yg(8) labelSize],...
            'String','Change Settings');
    fig.stop2 = uicontrol('Style','pushButton',...
            'Position',[xg(3) yg(9) buttonSize],...
            'String','Stop',...
            'tooltip','Stop Doing Pressure Control');
    fig.start2 = uicontrol('Style','pushButton',...
            'Position',[xg(3) yg(9) buttonSize],...
            'String','Start',...
            'tooltip','Start Doing Pressure Control');
        
   set(fig.GUI,'Name','Pressure Control')
   
   set(fig.GUI,'Visible','on')

end
